name: Build Cudy ImmortalWrt

on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

      - name: Build firmware
        shell: bash
        run: |
          bash ./build_cudy_immortalwrt.sh
          ls -ahl

      - name: Build firmware
        if: failure() && !cancelled()
        env:
          NPROC: 1
        shell: bash
        run: |
          bash ./build_cudy_immortalwrt.sh
          ls -ahl

      - name: Build firmware
        run: |
          ls -ahl .
          ls -ahl bin || true
          ls -ahl immortalwrt || true

      - name: Upload bin artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-bin
          path: immortalwrt/bin
          if-no-files-found: error

      - name: Upload bin artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-bin
          path: immortalwrt/bin/targets/mediatek/filogic/immortalwrt-mediatek-filogic-cudy_tr3000-v1-squashfs-sysupgrade.bin
          if-no-files-found: error

